### ISSUE TITLE
Broken links API testing

### ISSUE THREAD

**Issue by GaetanoRu** [microsoft/playwright.dev#1010]
**ACTION PERFORMED**
1. Open playwright.dev 
2. Click on "Docs"
3. From the "Guides" section click on API testing
4. Switch language

https://user-images.githubusercontent.com/68898674/231491678-27bbe0ec-a2f3-4a26-b74f-a5371ab1d8a3.mp4

**I attach the console logs** : [playwright.dev-1681308714506.txt](https://github.com/microsoft/playwright.dev/files/11212594/playwright.dev-1681308714506.txt)

**Comment by mxschmitt** [comment]
Thanks, will be fixed with the next release.
