### ISSUE TITLE
Document slowmo value in python docs

### ISSUE THREAD

**Issue by truthdoug** [microsoft/playwright.dev#1026]
The python documentation of the CLI arguments doesn't explain that `--slowmo` requires a value. The example shows a value but doesn't explain what the number means. Improve this (PR coming)

**Comment by truthdoug** [comment]
https://github.com/microsoft/playwright/pull/22669

**Comment by mxschmitt** [comment]
Fixed by https://github.com/microsoft/playwright/pull/22669 thanks!
