### ISSUE TITLE
Broken links for "Dockerfile.jammy"

### ISSUE THREAD

**Issue by shuuji3** [microsoft/playwright.dev#1055]
This page has a broken link: https://playwright.dev/docs/docker

<img width="860" alt="Screenshot 2023-05-22 at 13 34 27" src="https://github.com/microsoft/playwright.dev/assets/1425259/6220f491-7f7c-4cf5-9869-ddf67d6989db">

I'm reporting here since it looks like it requires to change the `common/links-*.md`. I'll make a PR to fix this issue soon.

**Comment by mxschmitt** [comment]
Thanks! Your fix should be live in 10-20 minutes: https://playwright.dev/docs/next/docker

(next channel only so far)

**Comment by shuuji3** [comment]
Thank you for reviewing. 🙂
