### ISSUE TITLE
A11y_.Playwright releases_AI4W Ensures elements with an ARIA role that require child roles contain them

### ISSUE THREAD

**Issue by tripathiakhil429** [microsoft/playwright.dev#1208]
[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-nikpap%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847543876&sdata=6wiDneF0tmnVt4CroW43rkfVbB%2BL%2BAAdn0nD7xR5hQM%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".

### GitHub Tags:
#A11ySev3; #A11yTCS; #DesktopWeb; #CELA_Playwrightreleases_Nov23; #Playwright releases
; #WCAG1.3.1; #AI4W;#WCP;#Element:EditField;#ChromiumEdge

### Environment Details:​
Application Name: Playwright releases
Chromium Edge version:Version 119.0.2151.44 (Official build) (64-bit)

### Repro Steps:

1. Hit the URL https://trace.playwright.dev/
2. Run fastpass

### Issue:
Ensures elements with an ARIA role that require child roles contain them (aria-required-children - https://accessibilityinsights.io/info-examples/web/aria-required-children)

Target application: Playwright Trace Viewer - https://trace.playwright.dev/?trace=blob%3Ahttps%3A%2F%2Ftrace.playwright.dev%2F650661b4-672b-45a0-85fd-16d0f9960fd1&traceFileName=sffd.png

Element path: .list-view

Snippet: <div class="list-view vbox" role="list" data-testid="actions-tree"><div class="list-view-content" tabindex="0"></div></div>

Related paths: 
  .list-view-content

### How to fix: 
Fix any of the following:
  Element has children which are not allowed: div[tabindex]
  Element uses aria-busy="true" while showing a loader

Environment: Microsoft Edge version 119.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.40.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

**Note:**
AI is not highlighting the controls which has issues due to The web page ([https://trace.playwright.dev/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftrace.playwright.dev%2F&data=05%7C01%7Cv-insett%40microsoft.com%7C53a3e71982014748d74e08dbdf20c8ce%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638349104182503821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sPsjweSLfdns670R%2FR%2BaOaE86gcIWUtSsBT%2Fxjq7qX4%3D&reserved=0) ) has "fetch" event listener which intercept and control network requests. This listener is not allowing download of CSS file that is why issues are not getting highlighted on target page.

**Comment by tripathiakhil429** [comment]
![image](https://github.com/microsoft/playwright.dev/assets/85679252/0117144e-305c-48c2-a387-98ab061ca0f6)

**Comment by mxschmitt** [comment]
These three issues are already fixed as part of the next release 1.40.

See https://trace.playwright.dev/next/ for our beta version.

**Comment by tripathiakhil429** [comment]
@mxschmitt _Is there any ETA by when the next release will be available for end users.

**Comment by mxschmitt** [comment]
> @mxschmitt _Is there any ETA by when the next release will be available for end users.

1-2 weeks.

**Comment by mxschmitt** [comment]
This is fixed now.
