### ISSUE TITLE
Disney+ Hotstar site is Access Denied

### ISSUE THREAD

**Issue by doggy8088** [microsoft/playwright.dev#1499]
In the homepage of the playwright.dev site, [Disney+ Hotstar](https://www.hotstar.com/) site is Access Denied for now.

![image](https://github.com/user-attachments/assets/63d38129-cce1-40c8-93a8-7c71abf234d6)

![image](https://github.com/user-attachments/assets/b0a5b0f3-0863-4d19-93d3-796db8849ff7)

https://github.com/microsoft/playwright.dev/blob/main/src/pages/index.tsx#L187

**Comment by mxschmitt** [comment]
While the site is available in the US, I also can't reach it from Germany. So probably they don't offer service in these countries, maybe whole Europe. We unfortunately can't do much on that end!

**Comment by doggy8088** [comment]
No problem. I just fired an issue. Thanks for your reply. :)
