### ISSUE TITLE
`Getting started - VS Code` language switching issue

### ISSUE THREAD

**Issue by doggy8088** [microsoft/playwright.dev#1500]
Here are the steps to reproduce the issue:

1. Open https://playwright.dev/docs/getting-started-vscode

2. Switch to Python language

    ![image](https://github.com/user-attachments/assets/7a09603f-ddc3-4566-bfdb-7a885f46d8bb)

3. Error shown

    ![image](https://github.com/user-attachments/assets/3ca8d71e-088d-4f33-bc34-298c271259bb)

There are some page only exist in Node.js language. The existing language switching mechanism have this issue.

**Comment by mxschmitt** [comment]
Not all guides are available in every language, we recommend to start from "/" or "/intro" when switching languages. Closing since this is a known issue and just a best-effort language switcher.
