### ISSUE TITLE
Extra slash leads to 'This page is not available ...' issue on playwright.dev on docs

### ISSUE THREAD

**Issue by Anutrix** [microsoft/playwright.dev#1560]
Following links show 'This page is not available for `<language-name>`.':
https://playwright.dev/python/docs/intro/
https://playwright.dev/java/docs/intro/
https://playwright.dev/dotnet/docs/intro/

But following are working fine:
https://playwright.dev/python/docs/intro/
https://playwright.dev/java/docs/intro/
https://playwright.dev/dotnet/docs/intro/
https://playwright.dev/docs/intro/
https://playwright.dev/docs/intro

Even last one for Node.js works.

So if you visit https://playwright.dev/docs/intro and click the language  dropdown to select any other language, it's fine.
But if you visit https://playwright.dev/docs/intro/ (notice the extra slash) and click the language dropdown to select any other language, suddenly Playwright has 0 Docs xD.

I came across this issue when clicking a link in the wild here: https://github.com/microsoft/playwright-dotnet/issues/1788#issuecomment-986084823.

**Comment by mxschmitt** [comment]
Looks like I had a typo when I was creating the comment. Usually our customers are always on the link without the trailing slash so I would prefer not fixing it since ideally they will never run into it.

**Comment by mxschmitt** [comment]
This is unfortunately not something we control - since its done by Docusaurus / GitHub Actions.

**Comment by Skn0tt** [comment]
Found a way for us to control it, I think: https://github.com/microsoft/playwright.dev/pull/1561

**Comment by Skn0tt** [comment]
Sorry, false alarm - that didn't work.
