### ISSUE TITLE
[docs]i18n plan

### ISSUE THREAD

**Issue by sasukeh** [microsoft/playwright.dev#410]
**Context**
I feel Playwright is super cool for E2E testing tool ever. However, There is no Japanese or some other langage documentation except English. 

**Ask**
Is there plan to translate documentation in Japanese or some other langageges so far at Playwright.dev?
I will be able to contribute as translater in Japanese in the future if there is the plan.

**Comment by mxschmitt** [comment]
There are currently no plans for translating the docs into other languages. I'll keep the issue open so we can get feedback on it and we can reconsider it in the future.

Thanks already for offering your support!

**Comment by debs-obrien** [comment]
closing this as I don't see us adding other languages for now especially as we continue to rework and improve the docs therefore keeping languages updated would be quite difficult
