### ISSUE TITLE
component testing

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright.dev#609]
Improve this section
add examples for vue and svelte
add links to demo projects
create different section under component testing with vue and react and svelte and move component testing to be more prominent in the sidebar (check with Pavel on if to do this while in preview or when out of preview)

**Comment by sand4rt** [comment]
Related to: https://github.com/microsoft/playwright/pull/18765

**Comment by debs-obrien** [comment]
closing this until we decide to invest more time in the component testing part of documentation
