### ISSUE TITLE
Documentation does not reflect new test explorer/playwright dropdowns

### ISSUE THREAD

**Issue by 1RossFisher1** [microsoft/playwright.dev#753]
The below dropdowns are not showing in the readme. 
![image](https://user-images.githubusercontent.com/109974928/185236552-6b8e4911-8fdb-400d-8d42-1d8cd989b941.png)
This icon no longer present
![image](https://user-images.githubusercontent.com/109974928/185236753-b871c6be-ba9d-4872-9bc9-97c6c9bcfa82.png)

Additional questions:

What does show and reuse browser do?
Do you select cancel when you wish to finish a recording?
What is the difference between record new and record from here?

**Comment by debs-obrien** [comment]
will be live once docs are released
