### ISSUE TITLE
[Documentation] Getting started - VS Code should show "Show output of tests"

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright.dev#767]
The Getting started - VS Code ( https://playwright.dev/docs/getting-started-vscode ) is a good introduction
to using Playwright in VS Code. However there is a little bit of information that can be added to help the user.

In the "View and Run All Tests" section, there is a small inconspicuous button that is used to reveal the test output.
See attached picture for what I mean. Updating the documentation in whatever way suitable will probably assist future
readers. 

Thanks,
![image](https://user-images.githubusercontent.com/8535034/189232461-ab8df78b-2ec7-4321-81b1-00597cd6c7e1.png)

**Comment by debs-obrien** [comment]
closing this as docs have been updated
