### ISSUE TITLE
Can Safari or stock Firefox be used?

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright.dev#803]
Should be explained here: https://playwright.dev/docs/browsers

We see this question asked over and over again.

**Comment by debs-obrien** [comment]
I am not sure I understand the question or answer. This page in docs talks about webkit and Firefox so I believe the question is already answered or what am I missing @mxschmitt

**Comment by mxschmitt** [comment]
It does not mention that Mozilla Firefox nor stock Safari via setting it in the executablePath does not work. I've seen 5+ users trying to do it. Imo we should mention inside Firefox and WebKit's heading that it only works with Playwright's build of them.
