### ISSUE TITLE
[Bug] Community showcase page not updating from base playwright repo?

### ISSUE THREAD

**Issue by daguar** [microsoft/playwright.dev#896]
Hi! I recently submitted this PR https://github.com/microsoft/playwright/pull/19712 which adds mention of the community-supported Ruby port to the Community Showcase page in docs: https://playwright.dev/docs/showcase

For some reason, neither locally nor in production is that change showing up; even though from looking around the playwright repo, that Markdown file appears to be the only source?

Opening this issue because I think it is likely related to how the docs build here than in the base repo. I'll keep investigating as I have time but figured I'd open for awareness and if anyone knows what might be going on already. Thanks!

**Comment by mxschmitt** [comment]
Docs are rolled daily from playwright repo into the @next version of playwright.dev, see here: https://playwright.dev/docs/next/showcase

**Comment by debs-obrien** [comment]
Hi @daguar that page is not really being maintained at the moment and therefore is not linked to from anywhere in docs.  This page probably should be removed so it doesn't show up or maintained and added to sidebar if we are going to keep it. Will keep you posted

**Comment by daguar** [comment]
Thank you @debs-obrien for the context! The links out to unofficial other-language ports is useful, I believe, so would love to keep that on some other page.

I'll also mention that I found the page via a Google search, so while it may be a bit implicitly-deprecated, it might be worth checking traffic to the page and what keywords people are searching when they end up there (via Google Search Console) since that provides more of a data-driven lens on what the user needs are that the page serves currently.

Thanks for all of y'all's work on such a great project!

**Comment by debs-obrien** [comment]
closing as this page has now been deleted from site
