### ISSUE TITLE
Duplicate code snippets or missing Bash/Powershell tabs

### ISSUE THREAD

**Issue by rafaljab** [microsoft/playwright.dev#977]
See the "Guides->Browsers" page for Node.js, section "Installing Google Chrome & Microsoft Edge" - https://playwright.dev/docs/browsers#installing-google-chrome--microsoft-edge 

There is a double snippet of `npx playwright install msedge` code.

![issue-pic](https://user-images.githubusercontent.com/16215171/224512092-ea6b247a-d46a-4a7f-b00d-3c9840ebc2e4.png)

I suppose this code should be in Bash/Powershell tabs.
Or the first code snippet should be for Chrome (as the text above might suggest).

**Comment by mxschmitt** [comment]
This is already fixed in the next version: https://playwright.dev/docs/next/browsers#installing-google-chrome--microsoft-edge and gets released in the next release.
